// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpepkI1mXzNaJ0-Gj0JMvyAT4sXiVIsYA',
    appId: '1:250520533383:web:4808beb42db4a7f8fdbb22',
    messagingSenderId: '250520533383',
    projectId: 'bdsm-78a7d',
    authDomain: 'bdsm-78a7d.firebaseapp.com',
    storageBucket: 'bdsm-78a7d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQectCoR06n6BvmIboH9N5vfoKhGXRQFg',
    appId: '1:250520533383:android:7287493056428f05fdbb22',
    messagingSenderId: '250520533383',
    projectId: 'bdsm-78a7d',
    storageBucket: 'bdsm-78a7d.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpepkI1mXzNaJ0-Gj0JMvyAT4sXiVIsYA',
    appId: '1:250520533383:web:73e7586bfcfa5251fdbb22',
    messagingSenderId: '250520533383',
    projectId: 'bdsm-78a7d',
    authDomain: 'bdsm-78a7d.firebaseapp.com',
    storageBucket: 'bdsm-78a7d.appspot.com',
  );
}
